server:
  port: 8085
  servlet:
    context-path: '/ecommerce-authuser/'

spring:
  application:
    name: authuser
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5433/authuser
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'

ecommerce:
  broker:
    exchange:
      userEvent: ecommerce-userevent
